#!/bin/sh /etc/rc.common

START=10

system_config() {
	hostname -F /etc/hostname

	ifconfig lo 127.0.0.1

	[ "$(hostname)" = "nb5" ] && export TZ=CET-1CEST-2,M3.5.0/02:00:00,M10.5.0/03:00:00
}

mount_all() {
	mount -a
}

load_modules() {
	[ -d /etc/modules.d ] && {
		cd /etc/modules.d
		sed 's/^[^#]/insmod &/' $* | ash 2>&- || :
	}
}

topology_prepare() {
	brctl addbr lan0
	brctl addbr wan0
#	brctl addbr hotspot0
	[ -d /etc/adsl ] && {
		brctl addbr voip0
		brctl addbr tv0
	}
}

start() {
	system_config

	mount_all

	[ -d /etc/adsl ] && mkdir -p /var/adsl
	mkdir -p /var/run
	mkdir -p /var/log
	mkdir -p /var/lock
	mkdir -p /var/state
	mkdir -p /var/db
	mkdir -p /var/chilli
	mkdir -p /var/voip
	mkdir -p /var/ppp
	mkdir -p /var/dhcp
	mkdir -p /var/ntp
	mkdir -p /var/tmp
	chmod a+rw /var/tmp
	chmod a+rwx /tmp
	mkdir /tmp/autoconf

	grep -q squashfs /proc/mounts && cp /usr/sbin/flashcp /tmp/flashcp

	ln -s /dev/ring0 /var/log/daemon.log
	ln -s /dev/ring1 /var/log/kern.log
	ln -s /dev/ring2 /var/log/voip_proto.log
	ln -s /dev/ring3 /var/log/voip.log
	ln -s /dev/ring4 /var/log/messages
	ln -s /dev/ring5 /var/log/syslog
	ln -s /dev/ring6 /var/log/fastcgi.log
	ln -s /dev/ring7 /var/log/voip_events.log
	ln -s /dev/ring8 /var/log/hotspot.log
	ln -s /dev/ring9 /var/log/backup.log
	ln -s /dev/ring10 /var/log/status.log
	ln -s /dev/ring11 /var/log/wlan.log
	ln -s /dev/null /var/log/lighttpd.log

	grep -q debugfs /proc/filesystems && mount -t debugfs debugfs /sys/kernel/debug

	topology_prepare

	load_modules /etc/modules.d/*

	chmod a+r /dev/mtd*
	[ "$(hostname)" != "nb5" ] && chmod a+w /dev/mtd2
	[ "$(hostname)" = "nb5" ] && chmod a+w /dev/mtd4
}
