#!/bin/sh /etc/rc.common

boot() {

	networks='phy switch vlan adsl xtm topology lan dhcpc ppp'

	for i in $networks; do
		[ -x /etc/init.d/$i ] && /etc/init.d/$i boot 2>&1
	done

	touch /var/state/networks
}
