#!/bin/sh /etc/rc.common

echo "[xtm] $$ $action"

start() {
	case "$(hostname)" in
		nb4|nb6)
			;;
		*)
			exit 0
	esac

	xtm start --rq0 256

	xtm operate tdte --add ubr
	xtm operate intf --state 1 enable
	xtm operate intf --state 2 enable

	# Generate PVC
	echo "xtm : creating PVC..."
	xtm operate conn --add 1.8.35 aal5 1 llcsnap_eth qos
	xtm operate conn --addq 1.8.35 66 1 --addq 1.8.35 66 2
	xtm operate conn --createnetdev 1.8.35 nas_8_35
	ip link set nas_8_35 address $(mac_addr 3) up

	xtmctl operate conn --add 1.8.36 aal5 1 llcsnap_eth qos
	xtmctl operate conn --addq 1.8.36 66 1 --addq 1.8.36 66 2
	xtmctl operate conn --createnetdev 1.8.36 nas_8_36
	ip link set nas_8_36 address $(mac_addr -- -1) up

	xtmctl operate conn --add 1.0.65 aal5 1 llcsnap_eth qos
	xtmctl operate conn --addq 1.0.65 66 1 --addq 1.0.65 66 2
	xtmctl operate conn --createnetdev 1.0.65 nas_0_65
	case "$(uname -r)" in
		2.6.21.7)
			ip link set nas_0_65 address $(mac_addr 2) up
			;;
		*)
			ip link set nas_0_65 address $(mac_addr 10) up

			# create macvlan on nas_8_35
			ip link add link nas_8_35 name mv0 type macvlan
			ip link set mv0 address $(mac_addr 2) up
			;;
	esac
}

stop() {
	case "$(hostname)" in
		nb4|nb6)
			;;
		*)
			exit 0
	esac

	case "$(uname -r)" in
		2.6.21.7)
			;;
		*)
			ip link del link name mv0
			ip link del link name mv1
			ip link del link name mv2
			;;
	esac

	xtm operate conn --deletenetdev 1.8.35
	xtm operate conn --delete 1.8.35
	xtm operate conn --deletenetdev 1.8.36
	xtm operate conn --delete 1.8.36
	xtm operate conn --deletenetdev 1.0.65
	xtm operate conn --delete 1.0.65

	xtm operate intf --state 1 disable
	xtm operate intf --state 2 disable

	xtm operate tdte --delete 1

	xtm stop
}
